// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyTourDuLichBE.Models;

public partial class Like
{
    public int Id { get; set; }

    public int UserId { get; set; }

    public int NewId { get; set; }

    public TimeSpan Timestamp { get; set; }

    public virtual New New { get; set; }
}