// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyTourDuLichBE.Models;

public partial class New
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string NewContent { get; set; }

    public int UserId { get; set; }

    public TimeSpan Timestamp { get; set; }

    public virtual ICollection<Like> Like { get; set; } = new List<Like>();

    public virtual User User { get; set; }
}