// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyTourDuLichBE.Models;

public partial class TourImage
{
    public int Id { get; set; }

    public string PhysicalPath { get; set; }

    public int? TourId { get; set; }

    public virtual Tour Tour { get; set; }
}