// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyTourDuLichBE.Models;

public partial class User
{
    public int Id { get; set; }

    public string UserName { get; set; }

    public string Password { get; set; }

    public string Avatar { get; set; }

    public virtual ICollection<Comment> Comment { get; set; } = new List<Comment>();

    public virtual ICollection<New> New { get; set; } = new List<New>();

    public virtual ICollection<UserRole> UserRole { get; set; } = new List<UserRole>();
}